### ISSUE TITLE
Keywords in parsed maps

### ISSUE THREAD

**Issue by ibdknox** [mmcgrana/clj-json#8]
What is the reason for not using keywords in the parsed maps? It seems like Clojure idiomatically favors keys that are keywords.

**Comment by lancepantz** [comment]
parse-string has an option to keywordize the keys, just pass true after the json string. This isn't the default behavior because clojure is not always guaranteed to allow `.` inside of keywords. It does at the moment, but according to the reader docs this isn't valid, so it could throw an exception in future versions.

**Comment by ibdknox** [comment]
fair enough. thanks!
